import type { AppEdge, AppNode } from '../types';

const formatTimestamp = (date = new Date()) => date.toLocaleString();

export const slugifyFilename = (value: string, extension: string) => {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);

  return `${slug || 'weavestudio-workflow'}-${new Date().toISOString().slice(0, 10)}.${extension}`;
};

const buildReviewSummary = (nodes: AppNode[]) => {
  const reviewNodes = nodes.filter((node) => node.type === 'review');
  if (reviewNodes.length === 0) {
    return 'No review nodes are currently defined. Add a Review node for human checkpoints.';
  }

  return reviewNodes
    .map((node, index) => {
      const requirement = node.data.reviewRequired ? 'Required' : 'Optional';
      return `${index + 1}. ${node.data.title || 'Untitled review'} - ${requirement}: ${
        node.data.description || 'No review note provided.'
      }`;
    })
    .join('\n');
};

const buildEdgeSummary = (nodes: AppNode[], edges: AppEdge[]) => {
  if (edges.length === 0) {
    return 'No edges are currently defined. Connect node handles to document process flow.';
  }

  const nodeTitleById = new Map(nodes.map((node) => [node.id, node.data.title || node.id]));
  return edges
    .map((edge, index) => {
      const source = nodeTitleById.get(edge.source) ?? edge.source;
      const target = nodeTitleById.get(edge.target) ?? edge.target;
      return `${index + 1}. ${source} -> ${target}`;
    })
    .join('\n');
};

const buildNodeInventory = (nodes: AppNode[]) => {
  if (nodes.length === 0) {
    return 'No nodes are currently on the canvas.';
  }

  return nodes
    .map((node, index) => {
      const description = node.data.description || 'No description provided.';
      const content = node.data.content || 'No node content provided.';
      return [
        `### ${index + 1}. ${node.data.title || 'Untitled node'}`,
        `- Type: ${node.type}`,
        `- Status: ${node.data.status || 'pending'}`,
        `- Description: ${description}`,
        `- Content: ${content}`,
      ].join('\n');
    })
    .join('\n\n');
};

const buildGeneratedOutput = (nodes: AppNode[]) => {
  const outputNodes = nodes.filter((node) => node.type === 'output');
  if (outputNodes.length === 0) {
    return [
      'No output node is currently defined.',
      'Add an Output node with reviewed final text to create a stronger deliverable preview.',
    ].join('\n');
  }

  return outputNodes
    .map((node, index) => {
      const description = node.data.description ? `\n_${node.data.description}_\n` : '';
      const content = node.data.content || 'No output content provided yet.';
      return `## Output ${index + 1}: ${node.data.title || 'Untitled output'}${description}\n${content}`;
    })
    .join('\n\n');
};

export const generateMarkdown = (
  nodes: AppNode[],
  edges: AppEdge[],
  title = 'Workflow Output',
): string => {
  const timestamp = formatTimestamp();

  return [
    `# ${title}`,
    `Generated by WeaveStudio on ${timestamp}.`,
    '',
    'This is a deterministic, local-first workflow export. It organizes user-provided node content and does not verify facts, infer truth, or replace human review.',
    '',
    '## Workflow Summary',
    `- Node count: ${nodes.length}`,
    `- Edge count: ${edges.length}`,
    `- Review checkpoints: ${nodes.filter((node) => node.type === 'review').length}`,
    '',
    '## Generated Output',
    buildGeneratedOutput(nodes),
    '',
    '## Review Checkpoints',
    buildReviewSummary(nodes),
    '',
    '## Process Flow',
    buildEdgeSummary(nodes, edges),
    '',
    '## Source Nodes',
    buildNodeInventory(nodes),
    '',
    '## Export Metadata',
    `- Workflow title: ${title}`,
    `- Export timestamp: ${new Date().toISOString()}`,
    '- Storage model: Browser localStorage',
    '- Generation model: Deterministic local formatting',
  ].join('\n');
};

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
};

export const exportMarkdownFile = (markdown: string, filename: string) => {
  downloadBlob(new Blob([markdown], { type: 'text/markdown;charset=utf-8' }), filename);
};

export const exportJsonFile = (nodes: AppNode[], edges: AppEdge[], title = 'Workflow Output') => {
  const data = {
    appName: 'WeaveStudio',
    title,
    exportTimestamp: new Date().toISOString(),
    generationModel: 'deterministic-local-formatting',
    reviewCheckpoints: nodes
      .filter((node) => node.type === 'review')
      .map((node) => ({
        id: node.id,
        title: node.data.title,
        required: !!node.data.reviewRequired,
        note: node.data.description,
      })),
    generatedOutput: buildGeneratedOutput(nodes),
    nodes,
    edges,
  };

  downloadBlob(
    new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8' }),
    slugifyFilename(title, 'json'),
  );
};

export const exportPdfFile = async (markdown: string, title = 'Workflow Output') => {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF();

  const lines = markdown.split('\n');
  let y = 20;
  const margin = 15;
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = doc.internal.pageSize.getWidth() - margin * 2;

  doc.setFont('helvetica', 'normal');

  lines.forEach((line) => {
    if (y > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }

    if (line.startsWith('# ')) {
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(line.replace('# ', ''), margin, y);
      y += 10;
      return;
    }

    if (line.startsWith('## ')) {
      doc.setFontSize(15);
      doc.setFont('helvetica', 'bold');
      doc.text(line.replace('## ', ''), margin, y);
      y += 8;
      return;
    }

    if (line.startsWith('### ')) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(line.replace('### ', ''), margin, y);
      y += 7;
      return;
    }

    if (line.trim() === '') {
      y += 4;
      return;
    }

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const wrapped = doc.splitTextToSize(line, contentWidth);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 5.5;
  });

  doc.save(slugifyFilename(title, 'pdf'));
};
