import { FileDown, FileJson, FileText } from 'lucide-react';

export const ExportsCenter = () => {
  return (
    <div className="flex-1 overflow-y-auto p-6 sm:p-8 max-w-5xl mx-auto w-full">
      <h1 className="text-3xl font-bold mb-8">Export Center</h1>
      <p className="text-gray-400 mb-8 max-w-2xl">
        WeaveStudio generates deterministic, structured outputs from your workflow. You can export workflow data
        into standard formats from the browser without a backend dependency.
      </p>

      <div className="space-y-8">
        <section className="bg-panel border border-border rounded-lg p-6">
          <div className="flex items-start space-x-4">
            <div className="p-3 bg-blue-900/30 text-blue-400 rounded-lg shrink-0">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold mb-2">Markdown Report (.md)</h2>
              <p className="text-gray-400 text-sm mb-4">
                Generates a structured markdown document with the workflow title, generated output, source nodes, edges,
                review checkpoints, and export timestamp.
              </p>
              <div className="bg-[#1e1e24] p-4 rounded-lg font-mono text-xs text-gray-300 border border-gray-800">
                # Proposal: Operations Upgrade<br /><br />
                Generated by WeaveStudio on the export timestamp.<br /><br />
                ## Generated Output<br />
                Reviewed workflow content appears here.
              </div>
            </div>
          </div>
        </section>

        <section className="bg-panel border border-border rounded-lg p-6">
          <div className="flex items-start space-x-4">
            <div className="p-3 bg-amber-900/30 text-amber-400 rounded-lg shrink-0">
              <FileJson className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold mb-2">Workflow Snapshot (.json)</h2>
              <p className="text-gray-400 text-sm mb-4">
                Exports the graph, nodes, edges, positions, review checkpoints, generated output, and metadata into a
                serialized JSON file.
              </p>
              <div className="bg-[#1e1e24] p-4 rounded-lg font-mono text-xs text-gray-300 border border-gray-800">
                &#123;<br />
                &nbsp;&nbsp;"appName": "WeaveStudio",<br />
                &nbsp;&nbsp;"generationModel": "deterministic-local-formatting",<br />
                &nbsp;&nbsp;"nodes": [...],<br />
                &nbsp;&nbsp;"edges": [...]<br />
                &#125;
              </div>
            </div>
          </div>
        </section>

        <section className="bg-panel border border-border rounded-lg p-6">
          <div className="flex items-start space-x-4">
            <div className="p-3 bg-purple-900/30 text-purple-400 rounded-lg shrink-0">
              <FileDown className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold mb-2">Print-Oriented PDF (.pdf)</h2>
              <p className="text-gray-400 text-sm mb-4">
                Generates a simple PDF document from the same deterministic markdown preview for stakeholders who prefer
                printable files.
              </p>
              <p className="text-xs text-gray-500 italic">
                Note: PDF export uses a basic text-mapping fallback. A richer layout designer is listed as a future
                enhancement.
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};
